import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import authenticated from "@/actions/auth/authenticated.action";
import { CartProvider } from "@/context/cart/cart-context";
import { Navigation } from "@/components/navbar/navigation";
import { navLinksData } from "@/components/navbar/data/userNavLinksData";
import ClientOnly from "@/components/client-only";
import ModalProvider from "@/context/modal/modal-context";
// import ClientProviders from "@/components/providers/client-providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // await
  const isAuthenticated = authenticated();

  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientOnly>
          <Providers authenticated={isAuthenticated}>
            <ModalProvider>
              <CartProvider>
                <Navigation navLinks={navLinksData} />
                {/* <div className="h-72 w-full"></div> */}
                {/* <div style={{ paddingTop: "500px" }}> */}
                {children}
                {/* </div> */}
              </CartProvider>
            </ModalProvider>
          </Providers>
        </ClientOnly>
      </body>
    </html>
  );
}
